
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.math.BigDecimal;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashutosh Sharma
 */
public class loginPage extends javax.swing.JFrame {
String name;
    /**
     * Creates new form loginPage
     */
    public loginPage(String s) {
        initComponents();
        //loginPage.getContentPane().setBackground( desiredColor );
        name=s;
        l1.setText(s);
                this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 122, 255));
        setForeground(java.awt.Color.red);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 600, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("HELLO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 70, 38);

        l1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(320, 10, 160, 38);

        p1.setText("enter");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(300, 170, 120, 30);

        t1.setText("Enter here");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(300, 100, 120, 30);

        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 70, 120, 30);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 140, 120, 30);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 220, 100, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\JavaApplication5\\WTM_logo_stack_small-e1522970678669.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 50, 360, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Search the table to find a record matching  
//the input Mobile no. 
String username=t1.getText();
String password= new String(p1.getPassword());
if (username.isEmpty()) 
//Execute this part if text field is blank
    {       t1.setText("");
           // p1.setText("");
            JOptionPane.showMessageDialog (this,"Enter the Username"); 
} 
else if (password.isEmpty())
    {       //t1.setText("");
            p1.setText("");
            JOptionPane.showMessageDialog (this,"Enter the Password"); 
} 
// This part is executed if a Mobile No is 
// input in the text field
 else  
{ 
    try
    {
    Class.forName("java.sql.DriverManager");  
    Connection con = (Connection)  
            DriverManager.getConnection 
            ("jdbc:mysql://localhost:3306/cms1", "root", "A7@qcnsar"); //Ash@824015
    Statement stmt = (Statement) con.createStatement();
    if(name.equals("Student")){
        //////////////////////////
                String query="SELECT * FROM student WHERE sid='"+(Integer.parseInt(username))+"' and pass = sha1('"+password+"');";  
               ResultSet rs=stmt.executeQuery(query);  

                    if (rs.next())
                    {   
                        String sname=rs.getString("sname");
                        //JOptionPane.showMessageDialog (this,name);  
                    homePageS obj = new homePageS(name,sname,username);
                    obj.setVisible(true);
                    this.dispose();

                    }
                       else    
                       JOptionPane.showMessageDialog (this,"Sorry!Please try again");  
    //////////////////////////////
    }else if(name.equals("Instructor")){
                    String query="SELECT * FROM instructor WHERE iid='"+Integer.parseInt(username)+"' and pass = sha1('"+password+"');";  
               ResultSet rs=stmt.executeQuery(query);  

               if (rs.next())
               {   
                  String sname=rs.getString("name");
                   //JOptionPane.showMessageDialog (this,n);  
               homePageI obj = new homePageI(name,sname,username);
               obj.setVisible(true);
               this.dispose();

               }
                  else    
                  JOptionPane.showMessageDialog (this,"Sorry!Please try again");  
    
    }
    
    ///////////////////////////////
    
   
    //////////////////////////////
    
    } 

 catch (Exception e)  
         {   
         JOptionPane.showMessageDialog(this, e.getMessage());  
         }
 } 


    
   
        


       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
